dist: trusty
sudo: required
language: python
python:
    - "3.5"
before_install: "nvm install 6.10.3"
install: "pip install -r requirements.txt && python all/talker/install_nltk_modules.py"
script: "python -m tornado.testing all/test_cases.py"



